#!/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

base=$(streamlink --stream-url http://es.euronews.com/live best | rev | cut -d/ -f2- | rev)

echo $base/playlist.m3u8